### ISSUE TITLE
1Password 5: "Cannot Fill Item in Web Browser"

### ISSUE THREAD

**Issue by stayradiated** [ravenac95/sudolikeaboss#1]
OS X 10.10 and 1Password 5.0.1.

Running `sudolikeaboss` displays the 1Password Mini window, but when I select an item it displays this error message:

**Cannot Fill Item in Web Browser**
_Web Browser is connected but its code signature could not be verified. Filling and other features are disabled until this configuration issue is resolved._

At first I thought maybe I could disable "Verify browser code signature" in the 1Password Preferences. But it didn't make any difference.

![image](https://cloud.githubusercontent.com/assets/1140167/4694415/0ca62f7c-57c8-11e4-8a7f-fd0acb69fcb3.png)

**Comment by yacitus** [comment]
Nothing happens when I try my keyboard shortcut in iTerm2.

Not surprisingly, when I run `SUDOLIKEABOSS_WEBSOCKET_URI="ws://127.0.0.1:16263/slab" /usr/local/bin/sudoleaboss` at the command-line, it doesn't return. I have installed the sudolikeaboss-workaround, and ran sudolikeaboss-setup-workaround, and restarted Chrome.

I noticed that after I run sudolikeaboss-setup-workaround, the 1Password extension is disabled in Chrome and Chrome reports: "This extension may have been corrupted." If I click on "Repair" it is re-enabled, but `SUDOLIKEABOSS_WEBSOCKET_URI="ws://127.0.0.1:16263/slab" /usr/local/bin/sudoleaboss` still hangs.

Note running `/usr/local/bin/sudolikeaboss` brings up 1Password, but then I get the "Cannot Fill Item in Web Browser" dialog.

**Comment by yacitus** [comment]
`/usr/local/bin/sudolikeaboss` works great (at the command-line and as the iTerm2 coprocess) with 1Password 5 Version 5.1.BETA-34 (510034), once I disabled "Verify browser code signature" in the Advanced tab of the 1Password preferences.

**Comment by ravenac95** [comment]
@yacitus I think chrome has been making updates that may render the workaround non-functional. I would highly suggest that people now just install the beta of 1password 5.1 I've been using it to great success on my end.

**Comment by aspushkinus** [comment]
1password 5.1 is out of beta and sudolikeaboss works like boss now - without workaround.

BTW, I'm not a big fan of installation instructions as a gif. Going to create a pull request for list-based installation instructions.

**Comment by a5e** [comment]
I tried first without the workaround and I did have the "Cannot Fill Item in Web Browser" error. Tried the workaround and still the same error. Then I saw that it was not needed anymore since I have 1P 5.1. I ran:
```
brew uninstall sudolikeaboss-workaround
brew uninstall sudolikeaboss
```
I restarted
```
brew install sudolikeaboss
```
Still got the same issue, any idea what I'm missing ?

**Comment by aspushkinus** [comment]
Even though the workaround is no longer necessary, you need to still uncheck the "Verify browser code signature" checkbox in 1Password 5.1 settings:

![preferences](https://cloud.githubusercontent.com/assets/889219/6270365/a69a0726-b816-11e4-9b96-558ddeb00378.png)

**Comment by a5e** [comment]
@aspushkinus thanks, I thought the workaround was a way to keep it checked, this paragraph is not very clear in the README, will do a PR.

**Comment by kgadek** [comment]
Works for me without workaround.

```bashsession
$ sudolikeaboss --version
sudolikeaboss version 0.2.0

$ sw_vers -productVersion
10.11.1
```
```
1Password 5
Version 5.4.1 (541003)
```

**Comment by rodneyo** [comment]
Awesome! iterm2 plugin.  Thank you !!!
